### ISSUE TITLE
Ch17 Sample Exercise 2

### ISSUE THREAD

**Issue by danyeu** [bmuschko/ckad-study-guide#3]
I'm getting `services is forbidden` even after applying all manifests in the answers folder.

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "services is forbidden: User \"system:serviceaccount:t23:api-call\" cannot list resource \"services\" in API group \"\" in the namespace \"default\"",
  "reason": "Forbidden",
  "details": {
    "kind": "services"
  },
  "code": 403

**Comment by danyeu** [comment]
I suggest it be explicit in the RoleBinding manifest that the namespace should be default, as RoleBindings that bind ClusterRoles restrict the ClusterRole to it's namespace.
https://github.com/bmuschko/ckad-study-guide/blob/878abdb34b4ad5b9cd601b680874ce36c5dd65fb/app-a/ch17/service-list/rolebinding.yaml#L4

**Comment by rethab** [comment]
I've created a `ClusterRoleBinding` instead of a `RoleBinding` to make it work:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: serviceaccount-service-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-services-clusterrole
subjects:
- kind: ServiceAccount
  name: api-call
  namespace: t23
```

/cc @bmuschko
