### ISSUE TITLE
Chapter 20 Example 3: fsGroup does not exist in container's security context

### ISSUE THREAD

**Issue by rethab** [bmuschko/ckad-study-guide#5]
This is the example 20-3:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fs-secured
spec:
  containers:
  - image: nginx:1.25.3
    name: secured-container
    securityContext:
      fsGroup: 3500
    volumeMounts:
    - name: data-volume
      mountPath: /data/app
  volumes:
  - name: data-volume
    emptyDir: {}
```

It can also be found here: https://github.com/bmuschko/ckad-study-guide/blob/master/ch20/pod-file-system-group.yaml

When applying this, I get an error:

```bash
> k apply -f https://raw.githubusercontent.com/bmuschko/ckad-study-guide/refs/heads/master/ch20/pod-file-system-group.yaml
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/bmuschko/ckad-study-guide/refs/heads/master/ch20/pod-file-system-group.yaml": Pod in version "v1" cannot be handled as a Pod: strict decoding error: unknown field "spec.containers[0].securityContext.fsGroup"
```

Looking SecurityContext (which is used in containers from what I can tell) it does not seem to have a field `fsGroup`: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#securitycontext-v1-core

However, the PodSecurityContext (security context on pod level) has it: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#podsecuritycontext-v1-core

/cc @bmuschko
